name: Build and Deploy docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

jobs:
    docs:
      name: build and deploy docs
      runs-on: ubuntu-latest

      steps:      
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip

            # Pin sphinx to an older version until sphinx-multiversion is fixed
            # see
            # https://github.com/sphinx-contrib/multiversion/issues/201
            # https://github.com/sphinx-contrib/multiversion/pull/202
            python -m pip install "sphinx<8.2" sphinx-rtd-theme

            # This should pull in the fixed version of multiversion when its available
            python -m pip install "sphinx-multiversion @ git+https://github.com/sphinx-contrib/multiversion.git"

            python -m pip show sphinx sphinx-multiversion
            sphinx-build --version
            sphinx-multiversion --version || true
        - name: build docs
          run: |
            cd doc/sphinx
            make multiversion
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3.7.3
          if: ${{ github.repository_owner == 'lanl' && github.ref == 'refs/heads/main' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./doc/sphinx/_build/html
            force_orphan: true
